// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbClases
{
    public int Clase_Id { get; set; }

    [Display(Name = "Empleado")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Emple_Id { get; set; }
    [Display(Name = "Gimnasio")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Gimna_Id { get; set; }
    [Display(Name = "Clase")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Clase_Nombre { get; set; }
    [Display(Name = "Descripcion")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Clase_Descripcion { get; set; }

    [Display(Name = "Fecha")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Clase_Fecha { get; set; }

    [Display(Name = "Hora de Inicio")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public TimeOnly Clase_HoraInicio { get; set; }

    [Display(Name = "Hora de Fin")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public TimeOnly Clase_HoraFin { get; set; }

    [Display(Name = "Capacidad")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Clase_Capacidad { get; set; }

    public bool? Clase_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbEmpleados Emple { get; set; }

    public virtual tbGimnasios Gimna { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }
}