// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbDepartamentos
{
    [Display(Name = "Codigo")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Depar_Codigo { get; set; }

    [Display(Name = "Departamento")]
    [Required(ErrorMessage = "El campo {0} es requerido")]

    public string Depar_Descripcion { get; set; }

    public bool? Depar_Estado { get; set; }



    [Display(Name = "Usuario Creacion")]
    public int Usuar_Creacion { get; set; }

    [Display(Name = "Fecha de creacion")]

    public DateTime Fecha_Creacion { get; set; }

    [Display(Name = "Usuario modificacion")]

    public int? Usuar_Modificacion { get; set; }

    [Display(Name = "Fecha de modificacion")]

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbMunicipios> tbMunicipios { get; set; } = new List<tbMunicipios>();
}