// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionGimnasio.Models;

public partial class tbEjerciciosRutinasPorCliente
{
    public int EjRCl_Id { get; set; }

    public int EjRut_Id { get; set; }

    public int Clien_Id { get; set; }

    public int EjRCl_Series { get; set; }

    public int EjRCl_Repeticiones { get; set; }

    public int EjRCl_DescansoSegundos { get; set; }

    public bool? EjRCl_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbClientes Clien { get; set; }

    public virtual tbEjerciciosPorRutinas EjRut { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }
}