// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionGimnasio.Models;

public partial class tbEjerciciosPorRutinas
{
    public int EjRut_Id { get; set; }

    public int Rutin_Id { get; set; }

    public int Ejerc_Id { get; set; }

    public bool? EjRut_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbEjercicios Ejerc { get; set; }

    public virtual tbRutinas Rutin { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbEjerciciosRutinasPorCliente> tbEjerciciosRutinasPorCliente { get; set; } = new List<tbEjerciciosRutinasPorCliente>();
}