// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbEjercicios
{
    public int Ejerc_Id { get; set; }

    [Display(Name = "Ejercicio")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Ejerc_Nombre { get; set; }

    [Display(Name = "Descripcion ")]
    [Required(ErrorMessage = "El campo {0} es requerido")]

    public string Ejerc_Descripcion { get; set; }

    [Display(Name = "Musculo en que se enfoca")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Ejerc_MusculoPrincipal { get; set; }

    public bool? Ejerc_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbEjerciciosPorRutinas> tbEjerciciosPorRutinas { get; set; } = new List<tbEjerciciosPorRutinas>();
}