// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionGimnasio.Models;

public partial class tbMunicipios
{
    [Display(Name = "Codigo")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Munic_Codigo { get; set; }

    [Display(Name = "Municipio")]
    [Required(ErrorMessage = "El campo {0} es requerido")]

    public string Munic_Nombre { get; set; }

    [Display(Name = "Departamento")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Depar_Codigo { get; set; }

    [NotMapped]
    public string Depar_Descripcion { get; set; }

    public bool? Munic_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }


    [Display(Name = "Departamento")]
    public virtual tbDepartamentos Depar_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientes> tbClientes { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbEmpleados> tbEmpleados { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbGimnasios> tbGimnasios { get; set; } = new List<tbGimnasios>();
}