// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionGimnasio.Models;

public partial class tbPantallas
{
    public int Panta_Id { get; set; }

    public string Panta_Nombre { get; set; }

    public bool? Panta_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantalla { get; set; } = new List<tbRolesPorPantalla>();
}