// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbPagos
{
    public int Pagos_Id { get; set; }

    [Display(Name = "Cliente")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Clien_Id { get; set; }

    [Display(Name = "Plan")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Plane_Id { get; set; }

    [Display(Name = "Metodo De Pago")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int MetPa_Id { get; set; }

    [Display(Name = "Fecha De Pago")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public DateTime Pagos_Fecha { get; set; }

    public bool? Pagos_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    [Display(Name = "Cliente")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public virtual tbClientes Clien { get; set; }

    [Display(Name = "Metodo De Pago")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public virtual tbMetodosDePago MetPa { get; set; }

    [Display(Name = "Plan")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public virtual tbPlanes Plane { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }
}