// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbPlanes
{
    public int Plane_Id { get; set; }

    [Display(Name = "Nombre")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Plane_Nombre { get; set; }

    [Display(Name = "Descripcion")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Plane_Descripcion { get; set; }

    [Display(Name = "Duración")]
    [Required(ErrorMessage = "El campo {0} es requerido")]

    public int Plane_DuracionDias { get; set; }

    [Display(Name = "Precio")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public double Plane_Precio { get; set; }

    public bool? Plane_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPagos> tbPagos { get; set; } = new List<tbPagos>();
}