// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionGimnasio.Models;

public partial class tbRolesPorPantalla
{
    public int RolPa_Id { get; set; }

    public int Roles_Id { get; set; }

    public int Panta_Id { get; set; }

    public bool? RolPa_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbPantallas Panta { get; set; }

    public virtual tbRoles Roles { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }
}