// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionGimnasio.Models;

public partial class tbRutinas
{
    public int Rutin_Id { get; set; }

    [Display(Name = "Nombre de la rutina")]
    [Required(ErrorMessage = "El campo {0} es requerido")]

    public string Rutin_Nombre { get; set; }

    public bool? Rutin_Estado { get; set; }

    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbEjerciciosPorRutinas> tbEjerciciosPorRutinas { get; set; } = new List<tbEjerciciosPorRutinas>();
}