// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionGimnasio.Models;

public partial class tbUsuarios
{
    public int Usuar_id { get; set; }

    [Display(Name = "Nombre Usuario")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Usuar_Nombre { get; set; }

    [Display(Name = "Contraseña")]
    [DataType(DataType.Password)]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public string Usuar_Contrasena { get; set; }

    [Display(Name = "Empleado")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Emple_id { get; set; }

    [Display(Name = "Rol")]
    [Required(ErrorMessage = "El campo {0} es requerido")]
    public int Roles_id { get; set; }

    [NotMapped]
    [Display(Name = "Contraseña Antigua")]
    [Required(ErrorMessage = "La contraseña actual es obligatoria.")]
    [DataType(DataType.Password)]
    public string Usuar_ContrasenaVieja { get; set; }
    [NotMapped]
    [Display(Name = "Contraseña Nueva")]
    [Required(ErrorMessage = "La nueva contraseña es obligatoria.")]
    [DataType(DataType.Password)]
    public string Usuar_Contrasena1 { get; set; }
    [NotMapped]
    [Display(Name = "Confirmar Contraseña")]
    [Required(ErrorMessage = "La confirmación de la contraseña es obligatoria.")]
    [DataType(DataType.Password)]
    [Compare("Usuar_Contrasena1", ErrorMessage = "Las contraseñas no coinciden.")]
    public string Usuar_Contrasena2 { get; set; }


    public int Usuar_Creacion { get; set; }

    public DateTime Fecha_Creacion { get; set; }

    public int? Usuar_Modificacion { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    [Display(Name = "Admin")]
    public bool Usuar_EsAdmin { get; set; }

    public bool? Usuar_Estado { get; set; }

    public virtual tbEmpleados Emple { get; set; }

    public virtual ICollection<tbUsuarios> InverseUsuar_CreacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> InverseUsuar_ModificacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual tbRoles Roles { get; set; }

    public virtual tbUsuarios Usuar_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usuar_ModificacionNavigation { get; set; }

    public virtual ICollection<tbCargos> tbCargosUsuar_CreacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCargos> tbCargosUsuar_ModificacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbClases> tbClasesUsuar_CreacionNavigation { get; set; } = new List<tbClases>();

    public virtual ICollection<tbClases> tbClasesUsuar_ModificacionNavigation { get; set; } = new List<tbClases>();

    public virtual ICollection<tbClientes> tbClientesUsuar_CreacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbClientes> tbClientesUsuar_ModificacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsuar_CreacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsuar_ModificacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbEjerciciosPorRutinas> tbEjerciciosPorRutinasUsuar_CreacionNavigation { get; set; } = new List<tbEjerciciosPorRutinas>();

    public virtual ICollection<tbEjerciciosPorRutinas> tbEjerciciosPorRutinasUsuar_ModificacionNavigation { get; set; } = new List<tbEjerciciosPorRutinas>();

    public virtual ICollection<tbEjerciciosRutinasPorCliente> tbEjerciciosRutinasPorClienteUsuar_CreacionNavigation { get; set; } = new List<tbEjerciciosRutinasPorCliente>();

    public virtual ICollection<tbEjerciciosRutinasPorCliente> tbEjerciciosRutinasPorClienteUsuar_ModificacionNavigation { get; set; } = new List<tbEjerciciosRutinasPorCliente>();

    public virtual ICollection<tbEjercicios> tbEjerciciosUsuar_CreacionNavigation { get; set; } = new List<tbEjercicios>();

    public virtual ICollection<tbEjercicios> tbEjerciciosUsuar_ModificacionNavigation { get; set; } = new List<tbEjercicios>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsuar_CreacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsuar_ModificacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsuar_CreacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsuar_ModificacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbGimnasios> tbGimnasiosUsuar_CreacionNavigation { get; set; } = new List<tbGimnasios>();

    public virtual ICollection<tbGimnasios> tbGimnasiosUsuar_ModificacionNavigation { get; set; } = new List<tbGimnasios>();

    public virtual ICollection<tbMetodosDePago> tbMetodosDePagoUsuar_CreacionNavigation { get; set; } = new List<tbMetodosDePago>();

    public virtual ICollection<tbMetodosDePago> tbMetodosDePagoUsuar_ModificacionNavigation { get; set; } = new List<tbMetodosDePago>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsuar_CreacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsuar_ModificacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbPagos> tbPagosUsuar_CreacionNavigation { get; set; } = new List<tbPagos>();

    public virtual ICollection<tbPagos> tbPagosUsuar_ModificacionNavigation { get; set; } = new List<tbPagos>();

    public virtual ICollection<tbPantallas> tbPantallasUsuar_CreacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPantallas> tbPantallasUsuar_ModificacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPlanes> tbPlanesUsuar_CreacionNavigation { get; set; } = new List<tbPlanes>();

    public virtual ICollection<tbPlanes> tbPlanesUsuar_ModificacionNavigation { get; set; } = new List<tbPlanes>();

    public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantallaUsuar_CreacionNavigation { get; set; } = new List<tbRolesPorPantalla>();

    public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantallaUsuar_ModificacionNavigation { get; set; } = new List<tbRolesPorPantalla>();

    public virtual ICollection<tbRoles> tbRolesUsuar_CreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesUsuar_ModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRutinas> tbRutinasUsuar_CreacionNavigation { get; set; } = new List<tbRutinas>();

    public virtual ICollection<tbRutinas> tbRutinasUsuar_ModificacionNavigation { get; set; } = new List<tbRutinas>();
}